# Generated by Django 3.0 on 2020-01-03 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(default=0)),
                ('team1_score', models.CharField(default='0', max_length=40)),
                ('overs_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('team2_score', models.CharField(default='0', max_length=40)),
                ('overs_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('comments', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='match_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('game_name', models.CharField(max_length=20)),
                ('game_type', models.CharField(max_length=20)),
                ('game_date', models.DateField(default=datetime.date.today)),
                ('game_time', models.TimeField(default='00:00')),
                ('ac_start_time', models.IntegerField(default=0)),
                ('live_status', models.BooleanField(default=False)),
                ('match_place', models.CharField(max_length=100)),
                ('end_status', models.BooleanField(default=False)),
                ('game_id', models.IntegerField(default=0)),
                ('assignment_to', models.CharField(default='NIL', max_length=100)),
                ('final_discription', models.CharField(blank=True, max_length=100)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('final_team1', models.CharField(blank=True, max_length=20, null=True)),
                ('final_team2', models.CharField(blank=True, max_length=20)),
                ('invisble_comments', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='team_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_game', models.CharField(max_length=100)),
            ],
        ),
    ]
