# Generated by Django 3.0 on 2019-12-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='match_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('match_type', models.CharField(max_length=20)),
                ('match_status', models.BooleanField(default=False)),
                ('asssigment_code', models.IntegerField(default=0)),
                ('start_id', models.IntegerField()),
                ('final_discription', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
                ('final_team1', models.CharField(max_length=20)),
                ('final_team2', models.CharField(max_length=20)),
            ],
        ),
    ]
