# Generated by Django 3.0 on 2019-12-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_match_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_list',
            name='invisble_comments',
            field=models.CharField(default='ccds', max_length=100),
            preserve_default=False,
        ),
    ]
