# Generated by Django 3.0 on 2019-12-19 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_match_list_invisble_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_list',
            name='current_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match_list',
            name='end_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match_list',
            name='match_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='match_list',
            name='match_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='match_list',
            name='final_discription',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match_list',
            name='final_team1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match_list',
            name='final_team2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match_list',
            name='invisble_comments',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match_list',
            name='start_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_list',
            name='winner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
