# Generated by Django 3.0 on 2019-12-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191219_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_list',
            name='end_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match_list',
            name='final_discription',
            field=models.CharField(blank=True, default='fddfdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match_list',
            name='final_team1',
            field=models.CharField(blank=True, default='ddd', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match_list',
            name='final_team2',
            field=models.CharField(blank=True, default='fcdc', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match_list',
            name='invisble_comments',
            field=models.CharField(blank=True, default='ds', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match_list',
            name='start_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match_list',
            name='winner',
            field=models.CharField(blank=True, default='ddd', max_length=100),
            preserve_default=False,
        ),
    ]
