# Generated by Django 3.0 on 2019-12-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20191219_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_list',
            name='end_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
