# Generated by Django 3.0 on 2019-12-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20191219_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_basketball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField()),
                ('team1_change', models.IntegerField()),
                ('team1_time', models.TimeField()),
                ('team2_score', models.IntegerField()),
                ('team2_change', models.IntegerField()),
                ('team2_time', models.TimeField()),
                ('game_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='team_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='match_list',
            old_name='asssigment_code',
            new_name='asssignment_code',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='asssigment_code',
            new_name='asssignment_code',
        ),
        migrations.AddField(
            model_name='match_list',
            name='match_place',
            field=models.CharField(default='ll', max_length=100),
            preserve_default=False,
        ),
    ]
