# Generated by Django 3.0 on 2019-12-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191219_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_list',
            old_name='asssignment_code',
            new_name='assignment_code',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='asssignment_code',
            new_name='assignment_code',
        ),
    ]
