# Generated by Django 3.0 on 2019-12-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20191219_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_list',
            name='game_name',
            field=models.CharField(default='BASKETBALL-M', max_length=20),
            preserve_default=False,
        ),
    ]
