# Generated by Django 3.0 on 2019-12-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_match_list_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_data',
            name='team_game',
            field=models.CharField(default='ll', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game_basketball',
            name='game_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game_basketball',
            name='team1_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game_basketball',
            name='team1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game_basketball',
            name='team1_time',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='game_basketball',
            name='team2_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game_basketball',
            name='team2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game_basketball',
            name='team2_time',
            field=models.TimeField(default=0),
        ),
    ]
