# Generated by Django 3.0 on 2019-12-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20191220_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_basketball',
            name='team1_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='game_basketball',
            name='team2_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
