# Generated by Django 3.0 on 2019-12-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20191220_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_basketball',
            name='team1_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game_basketball',
            name='team2_edit',
            field=models.BooleanField(default=True),
        ),
    ]
