# Generated by Django 3.0 on 2019-12-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20191220_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_basketball',
            name='team2_edit',
            field=models.BooleanField(default=False),
        ),
    ]
