# Generated by Django 3.0 on 2019-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20191220_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_basketball_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField(default=0)),
                ('team1_change', models.IntegerField(default=0)),
                ('team1_time', models.TimeField(default='00:00')),
                ('team1_edit', models.BooleanField(default=False)),
                ('team2_edit', models.BooleanField(default=False)),
                ('team2_score', models.IntegerField(default=0)),
                ('team2_change', models.IntegerField(default=0)),
                ('team2_time', models.TimeField(default='00:00')),
                ('game_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='game_cricket_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.IntegerField(default=0)),
                ('inning_no', models.IntegerField(default=0)),
                ('over_no', models.IntegerField(default=0)),
                ('ball_1', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='game_football_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField(default=0)),
                ('team1_change', models.IntegerField(default=0)),
                ('team1_time', models.TimeField(default='00:00')),
                ('team1_edit', models.BooleanField(default=False)),
                ('team2_edit', models.BooleanField(default=False)),
                ('team2_score', models.IntegerField(default=0)),
                ('team2_change', models.IntegerField(default=0)),
                ('team2_time', models.TimeField(default='00:00')),
                ('game_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='game_football_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField(default=0)),
                ('team1_change', models.IntegerField(default=0)),
                ('team1_time', models.TimeField(default='00:00')),
                ('team1_edit', models.BooleanField(default=False)),
                ('team2_edit', models.BooleanField(default=False)),
                ('team2_score', models.IntegerField(default=0)),
                ('team2_change', models.IntegerField(default=0)),
                ('team2_time', models.TimeField(default='00:00')),
                ('game_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='game_basketball',
            new_name='game_basketball_1',
        ),
    ]
