# Generated by Django 3.0 on 2019-12-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20191220_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_list',
            name='assignment_to',
            field=models.CharField(default='NIL', max_length=100),
        ),
    ]
