# Generated by Django 3.0 on 2019-12-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_match_list_assignment_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_list',
            name='assignment_transfer_status',
            field=models.BooleanField(default=False),
        ),
    ]
