# Generated by Django 3.0 on 2019-12-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_match_list_assignment_transfer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(default=0)),
                ('team1_score', models.CharField(default='0/0', max_length=40)),
                ('overs_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('team2_score', models.CharField(default='0/0', max_length=40)),
                ('overs_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='game_basketball_1',
        ),
        migrations.DeleteModel(
            name='game_basketball_2',
        ),
        migrations.DeleteModel(
            name='game_cricket_1',
        ),
        migrations.DeleteModel(
            name='game_football_1',
        ),
        migrations.DeleteModel(
            name='game_football_2',
        ),
        migrations.DeleteModel(
            name='user_data',
        ),
        migrations.RenameField(
            model_name='match_list',
            old_name='assignment_transfer_status',
            new_name='end_status',
        ),
        migrations.RenameField(
            model_name='match_list',
            old_name='match_date',
            new_name='game_date',
        ),
        migrations.RenameField(
            model_name='match_list',
            old_name='assignment_code',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='match_list',
            old_name='match_time',
            new_name='game_time',
        ),
        migrations.RenameField(
            model_name='match_list',
            old_name='match_type',
            new_name='game_type',
        ),
        migrations.RenameField(
            model_name='match_list',
            old_name='current_status',
            new_name='live_status',
        ),
        migrations.RemoveField(
            model_name='match_list',
            name='end_id',
        ),
        migrations.RemoveField(
            model_name='match_list',
            name='match_status',
        ),
        migrations.RemoveField(
            model_name='match_list',
            name='start_id',
        ),
    ]
