# Generated by Django 3.0 on 2020-01-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20191231_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_list',
            name='ac_start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
