# Generated by Django 3.0 on 2020-01-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_match_list_ac_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_list',
            name='ac_start_time',
            field=models.IntegerField(default=0),
        ),
    ]
