# Generated by Django 3.0 on 2020-01-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20200102_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_list',
            name='team1_score',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='game_list',
            name='team2_score',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
